server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    mongodb:
      url: mongodb+srv://Hanif:marbling1293@cluster0.djiwm.mongodb.net/notify?retryWrites=true&w=majority

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

auth:
  jwt:
    secret: jdaijsdiofaugiabgar