server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notify?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hanif1293@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

#  data:
#    mongodb:
#      url: mongodb+srv://Hanif:marbling1293@cluster0.djiwm.mongodb.net/notify?retryWrites=true&w=majority
#
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

auth:
  jwt:
    secret: jdaijsdiofaugiabgar