name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: grant privileges to gradlew
        run: chmod +x gradlew

      - name: run test
        run: ./gradlew test --info

      - name: run build
        run: ./gradlew clean build -x test